repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.0
    hooks:
      - id: prettier
        files: ^.*\.(js|jsx|ts|tsx|json|css|scss|md|mdx|toml|xml)$
        exclude: (^.*/plasmic/.*$|.md$)
        additional_dependencies:
          - prettier
          - prettier-plugin-organize-imports
          - typescript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.0
    hooks:
      - id: prettier
        files: ^.*/plasmic/.*\.(js|jsx|ts|tsx|json|css|scss|md|toml|xml)$
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: ^.*/__snapshots__/.*$
