name: Build and deploy

on: push

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: pre-commit
        uses: pre-commit/action@v2.0.0
